### ISSUE TITLE
Open-source licencing

### ISSUE THREAD

**Issue by krame505** [melt-umn/lambda-calculus#3]
@ericvanwyk 
Sorry to re-hash this again, but I just went through Google's open-source software training, and essentially I am only allowed to freely contribute to public projects on Github that have an open-source license - i.e. Google holds the copyright for any of my contributions, and I am not authorized to put anything into the public domain.  
So if I need to make any changes on this repo this summer, we need to have it under an open-source license.

**Comment by ericvanwyk** [comment]
No problem.  I'm sure they won't care about these, but best to play by the rules if that makes you more comfortable.  Go ahead and make the necessary changes to this one or any others.
